// <auto-generated />
using System;
using CodeHealthHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeHealthHub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260118060453_ChangeIssuesModelAgain")]
    partial class ChangeIssuesModelAgain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("CodeHealthHub.Models.Measure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metric")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectScanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectScanId");

                    b.ToTable("Measures");
                });

            modelBuilder.Entity("CodeHealthHub.Models.PieChartColour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("HexCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PieChartColours");
                });

            modelBuilder.Entity("CodeHealthHub.Models.ProjectIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreationDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Debt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Effort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SonarQubeProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SonarQubeProjectId");

                    b.ToTable("ProjectIssues");
                });

            modelBuilder.Entity("CodeHealthHub.Models.ProjectScan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AnalysisDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SonarQubeProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SonarQubeProjectId");

                    b.ToTable("ProjectScans");
                });

            modelBuilder.Entity("CodeHealthHub.Models.SonarQubeInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SonarQubeInstances");
                });

            modelBuilder.Entity("CodeHealthHub.Models.SonarQubeProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DeveloperCostPerHour")
                        .HasColumnType("REAL");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastAnalysisDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumOfDevelopers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SonarQubeInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SonarQubeInstanceId");

                    b.ToTable("SonarQubeProjects");
                });

            modelBuilder.Entity("CodeHealthHub.Models.Measure", b =>
                {
                    b.HasOne("CodeHealthHub.Models.ProjectScan", "ProjectScan")
                        .WithMany("Measures")
                        .HasForeignKey("ProjectScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectScan");
                });

            modelBuilder.Entity("CodeHealthHub.Models.ProjectIssue", b =>
                {
                    b.HasOne("CodeHealthHub.Models.SonarQubeProject", "SonarQubeProject")
                        .WithMany("ProjectIssues")
                        .HasForeignKey("SonarQubeProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SonarQubeProject");
                });

            modelBuilder.Entity("CodeHealthHub.Models.ProjectScan", b =>
                {
                    b.HasOne("CodeHealthHub.Models.SonarQubeProject", "SonarQubeProject")
                        .WithMany("ProjectScans")
                        .HasForeignKey("SonarQubeProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SonarQubeProject");
                });

            modelBuilder.Entity("CodeHealthHub.Models.SonarQubeProject", b =>
                {
                    b.HasOne("CodeHealthHub.Models.SonarQubeInstance", "SonarQubeInstance")
                        .WithMany("Projects")
                        .HasForeignKey("SonarQubeInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SonarQubeInstance");
                });

            modelBuilder.Entity("CodeHealthHub.Models.ProjectScan", b =>
                {
                    b.Navigation("Measures");
                });

            modelBuilder.Entity("CodeHealthHub.Models.SonarQubeInstance", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("CodeHealthHub.Models.SonarQubeProject", b =>
                {
                    b.Navigation("ProjectIssues");

                    b.Navigation("ProjectScans");
                });
#pragma warning restore 612, 618
        }
    }
}
