// <auto-generated />
using CodeHealthHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeHealthHub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("CodeHealthHub.Models.Measure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metric")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectScanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectScanId");

                    b.ToTable("Measures", (string)null);
                });

            modelBuilder.Entity("CodeHealthHub.Models.ProjectScan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnalysisDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SonarQubeProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SonarQubeProjectId");

                    b.ToTable("ProjectScans", (string)null);
                });

            modelBuilder.Entity("CodeHealthHub.Models.SonarQubeInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SonarQubeInstances", (string)null);
                });

            modelBuilder.Entity("CodeHealthHub.Models.SonarQubeProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DeveloperCostPerHour")
                        .HasColumnType("REAL");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastAnalysisDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumOfDevelopers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SonarQubeInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SonarQubeInstanceId");

                    b.ToTable("SonarQubeProjects", (string)null);
                });

            modelBuilder.Entity("CodeHealthHub.Models.Measure", b =>
                {
                    b.HasOne("CodeHealthHub.Models.ProjectScan", "ProjectScan")
                        .WithMany("Measures")
                        .HasForeignKey("ProjectScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectScan");
                });

            modelBuilder.Entity("CodeHealthHub.Models.ProjectScan", b =>
                {
                    b.HasOne("CodeHealthHub.Models.SonarQubeProject", "SonarQubeProject")
                        .WithMany("ProjectScans")
                        .HasForeignKey("SonarQubeProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SonarQubeProject");
                });

            modelBuilder.Entity("CodeHealthHub.Models.SonarQubeProject", b =>
                {
                    b.HasOne("CodeHealthHub.Models.SonarQubeInstance", "SonarQubeInstance")
                        .WithMany("Projects")
                        .HasForeignKey("SonarQubeInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SonarQubeInstance");
                });

            modelBuilder.Entity("CodeHealthHub.Models.ProjectScan", b =>
                {
                    b.Navigation("Measures");
                });

            modelBuilder.Entity("CodeHealthHub.Models.SonarQubeInstance", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("CodeHealthHub.Models.SonarQubeProject", b =>
                {
                    b.Navigation("ProjectScans");
                });
#pragma warning restore 612, 618
        }
    }
}
