// <auto-generated />
using System;
using CodeHealthHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeHealthHub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeHealthHub.Models.Measure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Metric")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectScanId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectScanId");

                    b.ToTable("Measures");
                });

            modelBuilder.Entity("CodeHealthHub.Models.PieChartColour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HexCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PieChartColours");
                });

            modelBuilder.Entity("CodeHealthHub.Models.ProjectIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Debt")
                        .HasColumnType("int");

                    b.Property<int?>("Effort")
                        .HasColumnType("int");

                    b.Property<string>("IssueKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SonarQubeProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SonarQubeProjectId");

                    b.ToTable("ProjectIssues");
                });

            modelBuilder.Entity("CodeHealthHub.Models.ProjectScan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnalysisDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SonarQubeProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SonarQubeProjectId");

                    b.ToTable("ProjectScans");
                });

            modelBuilder.Entity("CodeHealthHub.Models.SonarQubeInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SonarQubeInstances");
                });

            modelBuilder.Entity("CodeHealthHub.Models.SonarQubeProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("DeveloperCostPerHour")
                        .HasColumnType("float");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastAnalysisDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumOfDevelopers")
                        .HasColumnType("int");

                    b.Property<int>("SonarQubeInstanceId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SonarQubeInstanceId");

                    b.ToTable("SonarQubeProjects");
                });

            modelBuilder.Entity("CodeHealthHub.Models.Measure", b =>
                {
                    b.HasOne("CodeHealthHub.Models.ProjectScan", "ProjectScan")
                        .WithMany("Measures")
                        .HasForeignKey("ProjectScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectScan");
                });

            modelBuilder.Entity("CodeHealthHub.Models.ProjectIssue", b =>
                {
                    b.HasOne("CodeHealthHub.Models.SonarQubeProject", "SonarQubeProject")
                        .WithMany("ProjectIssues")
                        .HasForeignKey("SonarQubeProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SonarQubeProject");
                });

            modelBuilder.Entity("CodeHealthHub.Models.ProjectScan", b =>
                {
                    b.HasOne("CodeHealthHub.Models.SonarQubeProject", "SonarQubeProject")
                        .WithMany("ProjectScans")
                        .HasForeignKey("SonarQubeProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SonarQubeProject");
                });

            modelBuilder.Entity("CodeHealthHub.Models.SonarQubeProject", b =>
                {
                    b.HasOne("CodeHealthHub.Models.SonarQubeInstance", "SonarQubeInstance")
                        .WithMany("Projects")
                        .HasForeignKey("SonarQubeInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SonarQubeInstance");
                });

            modelBuilder.Entity("CodeHealthHub.Models.ProjectScan", b =>
                {
                    b.Navigation("Measures");
                });

            modelBuilder.Entity("CodeHealthHub.Models.SonarQubeInstance", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("CodeHealthHub.Models.SonarQubeProject", b =>
                {
                    b.Navigation("ProjectIssues");

                    b.Navigation("ProjectScans");
                });
#pragma warning restore 612, 618
        }
    }
}
